### ISSUE TITLE
[Bug]: github-actions workflow to build and publish docker image failing

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-ci#130]
### Describe the bug

The github-actions workflow to build and publish docker image is failing with below error:
```
Error: buildx failed with: error: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c /usr/local/bin/install-plugins.sh < plugins.txt" did not complete successfully: exit code: 255
```

### To reproduce

Trigger the workflow without explicitly setting up QEMU emulator.

**Comment by peterzhuamazon** [comment]
If this is for jenkins main node then no need to care about using buildx.

We can lock the jenkins mainnode to use x64.

It is not like we would ever run our Jenkins on arm64.

**Comment by gaiksaya** [comment]
This was regarding building the docker image on GHA. Nothing related to jenkins. Looks like the fix is in. Closing the issue.
Thanks!
