### ISSUE TITLE
Migrate existing deployment cdk code from opensearch-build repo opensearch-ci

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-ci#132]
### Is your feature request related to a problem? Please describe

There is a cdk application that generates stack that generates artifact s3 bucket, relevant roles and policies, a cloudfront distribution and lambda@edge to redirect requests to local artifact s3 bucket. The code is currently hosted in https://github.com/opensearch-project/opensearch-build/tree/main/deployment .

In order to make use of above mentioned components in public jenkins setup it makes more sense to implement that functionality in https://github.com/opensearch-project/opensearch-ci repo. 

### Describe the solution you'd like

After migrating the functionality the resources required to expose artifacts to public must be created in the new public jenkins account.

**Comment by zelinh** [comment]
[Triage] @rishabh6788 What's the current status for this issue? Could we close this one right now?

**Comment by peterzhuamazon** [comment]
Migrate perf test related agent node: https://github.com/opensearch-project/opensearch-ci/pull/153a

**Comment by gaiksaya** [comment]
Migration is complete via https://github.com/opensearch-project/opensearch-ci/pull/134
