### ISSUE TITLE
Correctly handle jenkins restart while hosting in Docker

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-ci#135]
https://www.jenkins.io/blog/2022/05/27/docker-image-new-lifecycle/

If you can see adding `safeRestart` in URL will not correctly restart Jenkins anymore if main node is hosted in Docker.
This article described the policy and configurations required for restoring the behavior.

Thanks.

**Comment by prudhvigodithi** [comment]
https://user-images.githubusercontent.com/28733332/173608278-fa4e923c-1d1a-425a-a7ee-2effede5a172.mov
