### ISSUE TITLE
[Bug]: Plugin Pipeline: Basic Steps failed to load with jenkins:2.332.3-lts-jdk8

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-ci#139]
### Describe the bug

2022-06-14 14:41:14.910+0000 [id=33]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Basic Steps v941.vdfe1b_a_132c64 (workflow-basic-steps)
java.io.IOException: Failed to load: Pipeline: Basic Steps (workflow-basic-steps 941.vdfe1b_a_132c64)
 - Failed to load: Pipeline: Nodes and Processes (workflow-durable-task-step 1144.vd77b_57189936)

### To reproduce

Start jenkins with `opensearchstaging/jenkins:2.332.3-lts-jdk8`
https://hub.docker.com/layers/jenkins/opensearchstaging/jenkins/2.332.3-lts-jdk8/images/sha256-f939f13223b480e448b7bdb12ad9b64846728ca678c28cd36cadb08d633bc6bf?context=explore

**Comment by rishabh6788** [comment]
This error is coming because dependent plugins need `workflow-api` plugin version 1162 or greater but during docker image build process the plugin version 1153 is getting installed. 
To fix go to `updates` and then install the version of the plugin mentioned in the UI and then restart jenkins.

**Comment by prudhvigodithi** [comment]
Worth exploring by adding `workflow-api:1164.v760c223ddb_32`.
