### ISSUE TITLE
[Bug]: Cannot find module 'aws-lambda' or its corresponding type declarations

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-ci#165]
### Describe the bug

When someone clones the repo and tries to run `npm run build`, we are seeing below error:
```
resources/cf-url-rewriter/cf-url-rewriter.ts:9:95 - error TS2307: Cannot find module 'aws-lambda' or its corresponding type declarations.

9 import { CloudFrontRequest, CloudFrontRequestCallback, CloudFrontRequestEvent, Context } from 'aws-lambda';
                                                                                                ~~~~~~~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! opensearch-ci-stack@0.1.0 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the opensearch-ci-stack@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Workaround currently is:
```
cd resources/cf-url-rewriter
npm install
```

### To reproduce

Clone this repo
Run `npm install` and then `npm run build`

### Expected behavior

npm install should take care of main as well as child node packages.

**Comment by gaiksaya** [comment]
One suggestion: https://stackoverflow.com/questions/31773546/the-best-way-to-run-npm-install-for-nested-folders

**Comment by rishabh6788** [comment]
running `npm run build` inside the resources dir first and then running it from root of the project would resolve the issue. Permanent solution will be move to the lamabda's package.json dependencies to project's package.json. 
I will take it up and create a PR @gaiksaya

**Comment by gaiksaya** [comment]
Since that project is not used anymore, can we just remove it? I believe we are not using that library/module now from opensource

**Comment by rishabh6788** [comment]
We do have the optional cdn stack in the opensource project.
