### ISSUE TITLE
Discard old builds and sort the jobs per view.

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-ci#168]
### Is your feature request related to a problem? Please describe

Currently the anonymous role in public jenkins shows all workflows. Create a new view for external community to show only relevant workflows

### Describe the solution you'd like
Can be categorized into 4 sections to start with:

- All : (present by default) exactly what we have today https://build.ci.opensearch.org/
- Build : Will contain all build pipelines which are distribution builds, docker builds as well as gradle checks, etc
- Test: Will contain all test pipelines example integ-test, perf-test, bwc-tests, etc
- Release: Will contain all release pipelines including promotion jobs, client releases, etc.

### Describe alternatives you've considered

Keep it as it is.

**Comment by prudhvigodithi** [comment]
[Triage], Sorting jobs per view is good idea to keep the Jenkins UI clean and all old not required jobs should be backed up and deleted.
