### ISSUE TITLE
Gradle Check Jenkins DSL is not in this repository.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-ci#17]
The Jenkins DSL for gradle checks should be visible in this repository.  Right now it is not executing from DSL and is not public.

[This](https://github.com/opensearch-project/opensearch-infra/tree/main/jenkins/jobs/OpenSearch_CI/PR_Checks) Should be moved into this repository.

**Comment by gaiksaya** [comment]
Gradle check is now public here: https://github.com/opensearch-project/OpenSearch/pull/2166
Closing this issue. Please reopen if any issues. Thanks!
