### ISSUE TITLE
[Bug]: Jenkins error high CPU utilization.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-ci#179]
### Describe the bug

Jenkins Runs fine, UI is up and builds work fine as well, but backend docker stats shows the CPU utilization percentage is too high and triggers the alerts.
Existing instance type is using [c5.4xlarge](https://github.com/opensearch-project/opensearch-ci/blob/main/lib/compute/jenkins-main-node.ts#L124) which has 30GB and 16CPU, lot of host resources are being unused.

### To reproduce

N/A

**Comment by rishabh6788** [comment]
The CPU alarm has been corrected. https://github.com/opensearch-project/opensearch-ci/pull/182
