### ISSUE TITLE
[Bug]: Missing `opensearch-test` used by perf tests

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-ci#184]
### Describe the bug

Role Reference
https://github.com/opensearch-project/opensearch-build/blob/main/vars/runPerfTestScript.groovy#L7-L12

### To reproduce

Re-run the Failed build link https://build.ci.opensearch.org/job/perf-test/323/console.

### Expected behavior

The policy or role should exists that is capable to execute the code to download the config.yml file.

**Comment by gaiksaya** [comment]
Fixed at the back end. Closing this issue!
