### ISSUE TITLE
[Bug]: Logs and reports from Gradle check is not accessible in OpenSearch

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/opensearch-ci#20]
### Describe the bug

The links in here are not accessible 
https://github.com/opensearch-project/OpenSearch/pull/1343#issuecomment-938905818

### To reproduce

Click on the links in this comment
https://github.com/opensearch-project/OpenSearch/pull/1343#issuecomment-938905818

**Comment by gaiksaya** [comment]
With jenkins being public all gradle logs are directly visible via given url. See https://build.ci.opensearch.org/job/gradle-check/
