### ISSUE TITLE
[Feature Request] Can we disable the requirement for admins to allow PRs to run gradle check

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-ci#21]
We have been living with the `start gradle check` passphrase for a while now and it is grating on our team of admins.

Lets disabling this feature for a trial period of 1 week and have a way to determine if this is something we should do long term.

Beforehand we need to make sure we have the correct monitoring in place to make sure that our CI fleet is health with the reduced human intervention.

**Comment by dblock** [comment]
Dup with https://github.com/opensearch-project/opensearch-ci/issues/4 ?
