### ISSUE TITLE
Bug: Fix cloudwatch alarm `MainNodeTooManyJenkinsProcessesFound`

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-ci#217]
### Describe the bug

The existing alarm `MainNodeTooManyJenkinsProcessesFound` sometimes shows false positives, the configured [procstat](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-procstat-process-metrics.html) alarm assumes there are more than one jenkins process.

Solution: 
Change the alarm in way instead of monitoring more than one process, monitor the main jenkins process and alert if the procstat java process `procstat_lookup_pid_count` jenkins.war is down.
This way to trigger the alarm when jenkins is down makes more sense.

### To reproduce

N/A

**Comment by gaiksaya** [comment]
closed via https://github.com/opensearch-project/opensearch-ci/pull/227
