### ISSUE TITLE
[Documentation] Which Jenkins Staging jobs need to be saved / removed 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-ci#22]
Here is a list of all of the jobs on the Jenkins staging system, lets figure out if we need them or not

Final results are in:
- [X] **Save** 1.0.0-maven-build-job 
- [X] **Save** 1.0.0-maven-sign-and-release
- [X] **Save** bundle-build
- [x] **Save** test-orchestration-pipeline
- [x] **Save** integ-test
- [x] **Save** bwc-test
- [x] **Save** perf-test
- [x] **Save** opensearch-java-maven-sign-and-release

---

- [x] **Remove** Single-Node-CDK-run
- [x] **Remove** fetch_build_pipelines_Sai
- [x] **Remove** fetch_bundles
- [x] **Remove** Integ-test-demo
- [x] **Remove** opensearch_bundle_integtest - legacy integ_test job
- [x] **Remove** perf-tests
- [x] **Remove** perf_test_owais - Has sample script to run perf test
- [x] **Remove** random_test
- [x] **Remove** bundle-build-inline-test
- [X] **Remove** bundle-build-petern
- [x] **Remove** bundle_pipeliness_1.0.1
- [x] **Remove** sample-cmd-testings
- [x] **Remove** Test-handalm
- [x] **Remove** test-job-1
- [x] **Remove** test-pipeline
- [x] **Remove**test-release-pipeline

**Comment by gaiksaya** [comment]
Relevant jobs moved to public jenkins. Thanks!
