### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/opensearch-ci#254]
### Is your feature request related to a problem? Please describe

As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the OpenSearch CI repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| OpenSearch CI | <li>- [x] </li> | <li>- [x] </li> | <li>- [ ] </li> |   |https://github.com/opensearch-project/opensearch-ci/issues/254 | 

### Describe the solution you'd like

I know that this repository has a different purpose then many of the others, so if there is anything you feel I should know when looking at testing for it please leave a comment. 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by rishabh6788** [comment]
AFAIK this repo doesn't need BWC as at any point in time there could only be one version of jenkins set up that could be running. We have no versioning policy and do not generate any artifacts for public to consume. 
Closing this issue, please feel free to reopen if you are not satisfied with the comment. @bbarani @gaiksaya
