### ISSUE TITLE
Make IMDSv2 calls mandatory in EC2 plugin

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-ci#270]
### Is your feature request related to a problem? Please describe

IMDSv1 calls are unauthorized and insecure. EC2 plugin used to deploy agent nodes in jenkins now supports making IMDSv2 calls which are secure and authenticated.
https://github.com/jenkinsci/ec2-plugin/blob/05cc8750ea196fc6141bd2487c0e0ce97fcd4940/README.md?plain=1#L340

### Describe the solution you'd like

On main node:
Add `requireImdsv2: true`

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.Instance.html#requireimdsv2
On Agent nodes:

Add `metadataTokensRequired: true,` in agent node configs. Default is false https://github.com/jenkinsci/ec2-plugin/blob/05cc8750ea196fc6141bd2487c0e0ce97fcd4940/src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly#L234

### Additional context

I tried adding both adnd deploying in my own jenkins, there was some config issue due to which agent nodes were unable to get instance profile
Error:
```
Failed to obtain credentials from EC2 instance profile: Unauthorized (Service: null; Status Code: 401; Error Code: null; Request ID: null; Proxy: null)
```

**Comment by gaiksaya** [comment]
The main node would still be Imdsv1 until we add `requireImdsv2: true`. However, after adding that agent nodes fail to launch.

**Comment by rishabh6788** [comment]
This [PR](https://github.com/opensearch-project/opensearch-ci/pull/273) updates the agent nodes to use IMDSv2 calls.
