### ISSUE TITLE
Make Jenkins instance publicly visible

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-ci#3]
**Is your feature request related to a problem? Please describe.**

Community wants to see which jobs are being run for CI/CD and logs.

**Describe the solution you'd like**

We are running a Jenkins instance that is currently private. Make it public.

**Comment by gaiksaya** [comment]
Duplicate issue for: https://github.com/opensearch-project/opensearch-ci/issues/2
Closing this issue.
