### ISSUE TITLE
[BUG] workflow-logs in cloudwatch loggroup does not get created after deployment

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-ci#329]
[BUG] workflow-logs in cloudwatch loggroup does not get created after deployment.
Only jenkins.log group is correctly created after the deployment.

Thanks.

[Acceptance Criterias]
- [ ] Should not need to restart the Jankins manually to fix the bug

**Comment by prudhvigodithi** [comment]
To fix this we need to manually restart Jenkins to fix the log group creation, need to automate this after the deployment, but the catch is since the OIDC is enabled need the authentication token to restart the Jenkins.

**Comment by peterzhuamazon** [comment]
Close this as it rarely happens and just need manual creation of log group.
