### ISSUE TITLE
Mechanism to verify json from Secret Manager for OIDC 

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-ci#34]
### Is your feature request related to a problem? Please describe

Currently, there is no mechanism to verify the json format and checking required fields for JSON put in the secret manager for OIDC. If there is something missing, the deployment will fail and there won't be descriptive error messages helping to debug the issue.

### Describe the solution you'd like

Write a mechanism to verify the JSON coming in from the secret manager for the OIDC credential and fail with descriptive error messages if any field is missing.

**Comment by gaiksaya** [comment]
We are using jenkins.yaml and configuration as code now that uses yaml object to parse.
