### ISSUE TITLE
Open-source all CI/CD scripts and configuration that runs in Jenkins   

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-ci#38]
Everything in GHA is open-source and in repos. The Jenkins scripts and configuration should follow suit. Anyone should be able to reproduce the OpenSearch CI/CD infrastructure after opensearch-project/opensearch-ci#2 and importing scripts and configuration that would be OSS. 

We have those scripts in source control now, but it remains private. Need to OSS those.

**Comment by gaiksaya** [comment]
All relevant jobs are public now and source controlled in public repo https://github.com/opensearch-project/opensearch-build/tree/main/jenkins
