### ISSUE TITLE
Jenkins upgrade to latest LTS:2.426.3

### ISSUE THREAD

**Issue by jordarlu** [opensearch-project/opensearch-ci#389]
### Is your feature request related to a problem? Please describe

We are currently running Jenkins `2.387.1`, and are planning to upgrade it to the latest LTS version, `2.440.2`.

There are CVEs and bugs pending to be fixed by upgrading Jenkins core to higher version
https://github.com/opensearch-project/opensearch-build/issues/3727

### Describe the solution you'd like

Upgrade Jenkins version to the latest LTS version.
At the time this issue is created, the latest LTS version is `2.440.2`
https://www.jenkins.io/doc/upgrade-guide/

Ref to the [previous upgrade](https://github.com/opensearch-project/opensearch-ci/issues/261), here are the steps to follow:

- [ ] 1. Upgrade docker image: Docker is the source of jenkins in this setup. Sample PR https://github.com/opensearch-project/opensearch-ci/pull/278
- [ ] 2. Upgrade Java (current Java 11): We should also consider upgrading Java version to 17 or 21 as the Jenkins will require Java 17 or 21 and drop support for Java 11 ETA in Fall 2024
https://www.jenkins.io/blog/2023/11/06/introducing-2-2-2-java-support-plan/#:~:text=Jenkins%202.426.,releases%20at%20any%20given%20time.
- [ ] 3. Bump jenkins core version in build.gradle: Associated repos https://github.com/opensearch-project/opensearch-build, https://github.com/opensearch-project/opensearch-build-libraries
- [ ] 4. Add documentation on how to upgrade. Documentation should mention EBS backing up as well.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by jordarlu** [comment]
Regarding the update of Java of our Jenkins nodes, we have the option to upgrade to either JDK17 or JDK21. Docker Hub currently provides support for both versions on the LTS 2.426.3:

For JDK21: [2.426.3-lts-jdk21](https://hub.docker.com/layers/jenkins/jenkins/2.426.3-lts-jdk21/images/sha256-e6a00b58d5df23cb3bb91501772ad80b5c68aab9b08efa6468e803ce124d2c3e?context=explore)
For JDK17: [2.426.3-lts-jdk17](https://hub.docker.com/layers/jenkins/jenkins/2.426.3-lts-jdk17/images/sha256-7d7371ab14525a0b0032e8a714f8ef6cfe5d0c37e3b9e6b68239543f2df9ba92?context=explore)

Given that JDK21 is relatively recent, and taking into account Jenkins' commitment to maintaining support for JDK17 until the early 2026, would it be ok for us to proceed with the upgrade to JDK17 for now?

**Comment by jordarlu** [comment]
We decided to move on with using JDK17

**Comment by jordarlu** [comment]
We have decided to move on with using JDK21 becasue it will be officially supported until 2029

**Comment by peterzhuamazon** [comment]
Related windows issues:
https://issues.jenkins.io/browse/JENKINS-73202

**Comment by peterzhuamazon** [comment]
We are changing to use jenkins:2.426.3-lts-jdk21.

**Comment by Divyaasm** [comment]
Jenkins  is successfully upgraded to 2.426.3

**Comment by peterzhuamazon** [comment]
A way to resolve is to pin:
```
/usr/share/jenkins/ref/plugins/durable-task.jpi
/usr/share/jenkins/ref/plugins/workflow-durable-task-step.jpi
```

in the docker image with specific versions:
https://updates.jenkins.io/download/plugins/durable-task/547.vd1ea_007d100c/durable-task.hpi
https://updates.jenkins.io/download/plugins/workflow-durable-task-step/1331.vc8c2fed35334/workflow-durable-task-step.hpi

Then we good.
