### ISSUE TITLE
[Enhancement] Add higher specs jenkins agent for integTest

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-ci#412]
[Enhancement] Add higher specs jenkins agent for integTest

Hi,

Our current setup is c54xlarge (16CPU 32GB) shared by 4 docker instances, each (4CPU 8GB).

We want to increase this setup to m54xlarge (16CPU 64GB) so that each will share (4CPU 16GB), similar to github after their updates here:
https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/

This could help us ensure stabilities of the runs even more, and we can lock onto the resources as well.

Thanks.

------

PRs:
* https://github.com/opensearch-project/opensearch-ci/pull/413
* https://github.com/opensearch-project/opensearch-build/pull/4594
* https://github.com/opensearch-project/opensearch-build/pull/4597
* https://github.com/opensearch-project/opensearch-ci/pull/417
* https://github.com/opensearch-project/opensearch-ci/pull/418
* https://github.com/opensearch-project/opensearch-build/pull/4642

**Comment by peterzhuamazon** [comment]
Re-open as Windows is pending changes, waiting for linux to show the results.

**Comment by peterzhuamazon** [comment]
This is completed.

**Comment by peterzhuamazon** [comment]
* https://github.com/opensearch-project/opensearch-ci/pull/433

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by dblock** [comment]
@peterzhuamazon Can this be closed now with the windows changes in?

**Comment by peterzhuamazon** [comment]
Hi @dblock there is a small bug that I am attempting to fix, waiting for merge:
* https://github.com/opensearch-project/opensearch-ci/pull/433

Thanks.
