### ISSUE TITLE
Deployment process for Beta

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-ci#43]
Plan how we can integrate the public OpenSearch-CI components into the internal infrastructure to manage deployments automatically.

Acceptance Criteria:
- [x] Figure how we can automatically pull this code base into the internal system
- [x] Update the internal tooling to pull in the CDK job for deployment
- [x] Support development environment deployment testing
- [x] Update any stack compatibility issues between environments
- [x] Verify that the beta environment gets automatic deployments.

**Comment by gaiksaya** [comment]
We were looking into how we can automatically pull this code base into the internal system. Below was one of the approach that I was trying to get to work:

```
GitHub -> Build and test -> Publish to npmjs -> Internal system to consume the package from npmjs.
```

However, we found out that propagation from npmjs to internal system making that package available would have significant amount of delay (few days) which is not ideal. 
We are trying to get more information to see if there are any workarounds and also working on other parallel approach. 
Thanks!

**Comment by peternied** [comment]
This process has been codified internally, now we can interate on fulling setting up the configuration for our environments.  Figure out any last minute requirements and get them done for release.
