### ISSUE TITLE
[Bug]: We need to specify the parameter flags when destroying a stack

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-ci#45]
### Describe the bug

When we destroy the cdk stack, we are currently required to specify the flag parameters. We should be able to destroy the stack without specifying the parameters.

### To reproduce

create a `CI-Dev` stack and destroy is using `cdk destroy CI-Dev`

### Expected behavior

We should be able to destroy the stack without specifying the parameter flags

**Comment by gaiksaya** [comment]
Currently useSSL and runwithOIDC are the two values do not have defaults. 
@rishabh6788 @prudhvigodithi  How about we make them false as default? In that way you do not need to pass these values while deploying/destroying the stack?

**Comment by rishabh6788** [comment]
This is not a bug it is the way CDK works, if there are any mandatory parameters that needed to be passed then they will be required for all cdk commands.

**Comment by rishabh6788** [comment]
This is not a bug and actually how cdk works. 
We can assign default values in code to avoid passing context from command line.
