### ISSUE TITLE
Dynamically load configuration from Jenkins.yaml

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-ci#47]
### Is your feature request related to a problem? Please describe

Currently, we need to manually change the `jenkins.yaml` file on the server and reload the config, or load the config file via the UI manually. We need a mechanism which detects the changes in `jenkins.yaml` and loads the changes on jenkins automatically.

Things to lookout for -
1. `jenkins.yaml` can potentially change the security config. We need to be careful for changes on the file.
2. OIDC changes reflect on config file. We would need to commit the oidc changes on the config file. Not doing that would revert the oidc setup changes.
3. reloading the config file requires to run a url. `username:passoword` will not work with oidc

### Describe the solution you'd like

Create a job on jenkins that detects the changes in config file on github and reloads it. We could use jenkins API tokens to run the urls, but they’ll will disappear after config reload.

**Comment by gaiksaya** [comment]
Even OIDC is loaded via jenkins.yaml now. Hence closing this issue.
Thanks!
