### ISSUE TITLE
[Bug]: Intermittent Apache Maven snapshot publication issues

### ISSUE THREAD

**Issue by reta** [opensearch-project/opensearch-ci#480]
### Describe the bug

Recently, we have been seeing intermittent Apache Maven snapshot publication issues across many repositories:

```
 Execution failed for task ':publishPluginZipPublicationToSnapshotsRepository'.
> Failed to publish publication 'pluginZip' to repository 'Snapshots'
   > Could not PUT 'https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/opensearch-security/2.16.0.0-SNAPSHOT/opensearch-security-2.16.0.0-20240717.154930-22.zip'. Received status code 403 from server: Forbidden
```

```
 For more on this, please refer to https://docs.gradle.org/8.9/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
10 actionable tasks: 10 executed
   > Could not PUT 'https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/client/opensearch-java/3.0.0-SNAPSHOT/opensearch-java-3.0.0-20240717.150831-245.jar'. Received status code 403 from server: Forbidden
```

Sometimes retrying the workflow helps but often does not.

### To reproduce

The issue is intermittent and could be observed across different repositories (see please additional context)

### Expected behavior

Publication should succeed

### Host / Environment

GA worflows

### Additional context

- https://github.com/opensearch-project/security/actions/runs/9977390466/job/27571888807
- https://github.com/opensearch-project/opensearch-java/actions/runs/9973820895/job/27569724501

**Comment by reta** [comment]
@peterzhuamazon FYI, I am not sure this is the right repository to submit the issue, please help find the right place, thank you

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon FYI, I am not sure this is the right repository to submit the issue, please help find the right place, thank you

Hi @reta , recently sonatype is doing a series of migration.
And we have worked with them yesterday to fixed bunch of publishing issues already.
Let us monitor for a bit and if we still see issues arise, we can capture the logs and send them a ticket again. Sorry about it.

**Comment by reta** [comment]
Closing this one, thanks @peterzhuamazon !
