### ISSUE TITLE
Support building individual components on ARM64 

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-ci#49]
**Is your feature request related to a problem? Please describe.**
I would like to execute Continuous Integration on arm64 hosts. 

**Describe the solution you'd like**
https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners to create arm64 at organization level, hence, this can be used by all OpenSearch projects.

**Describe alternatives you've considered**
Running integration tests manually from ARM64 laptop

**Additional context**
N/A

**Comment by rishabh6788** [comment]
Jenkins has arm64 agents to build and test components. closing.
