### ISSUE TITLE
CDN public artifact locations needs to be managed

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-ci#5]
For the existing instance we are hardcoding the path `https://ci.opensearch.org/ci/dbc` set as `CDN_PUBLIC_ARTIFACT_PREFIX` in the jenkins environment.  Is this the correct way to set this and how can we make sure this is unique for all deployments?

**Comment by gaiksaya** [comment]
Hi @peternied, can you elaborate more on what is the problem statement here? Is this issue similar to #111 ?

**Comment by peternied** [comment]
The non-public has a configured root path as `https://ci.opensearch.org/ci/dbc`, that `dbc` part of the path is an identifier to the jenkins cluster in operation via the CDN_PUBLIC_ARTIFACT_PREFIX variable.

This identifier is needed to redirect the ci.opensearch.org paths to the correct CDN bucket, see more details https://github.com/opensearch-project/opensearch-build/tree/main/deployment#overall-system

Ideally this value should be provided in the jenkins cluster setup since the account that controls ci.opensearch.org's cloudfront distribution needs to be updated to manage these resources.

**Comment by peternied** [comment]
Please feel free to update the description if you'd like.

**Comment by rishabh6788** [comment]
Closing against https://github.com/opensearch-project/opensearch-ci/pull/134
