### ISSUE TITLE
[META] Jenkins workflows and fleet monitoring

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-ci#50]
This is a meta issue tracking all subtasks for enabling Jenkins workflows and fleet monitoring

We already have some system level alarms configured as a part of the current cdk code. [CodeBase](https://github.com/opensearch-project/opensearch-ci/blob/main/lib/monitoring/ci-alarms.ts)
Apart from that we need to add below monitoring metrics:
1. SSL certs expiration and reporting
2. Alarms monitoring critical jenkins workflows
3. More..

**Comment by rishabh6788** [comment]
Opened #100 to work on setting up metrics for SSL Cert DaysToExpiry metric

**Comment by rishabh6788** [comment]
#100 merged and closed. 
Setting up alerts on existing instance level monitors in progress.

**Comment by bbarani** [comment]
@rishabh6788 Are we good to close this issue? Can you provide an update?
