### ISSUE TITLE
Workspaces should be automatically cleaned up after jobs finish running

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-ci#53]
Our system should delete the workspace and anything inside of it to prevent disk buildup.  It should be done in such a way that jobs do not need to be concerned about managing the system state, such as by explicitly making a `cleanWs` call.

**Comment by rishabh6788** [comment]
All our builds run on docker images that get destroyed after each run and we also have `postCleanup` action to clean up the workspace after a particular step or stage has been executed. 
Closing.
