### ISSUE TITLE
[Bug]: Hardcoding of rolename avoids redeployment of multiple stacks

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-ci#82]
### Describe the bug

Since IAM is global every new role name and policy name should be unique.
Having rolename hard coded throws error saying the role already exists and hence cannot create new role. 
https://github.com/opensearch-project/opensearch-ci/blob/main/lib/compute/jenkins-main-node.ts#L93

### To reproduce

Deploy stack in one region and try deploying the same stack in another region

### Expected behavior

Stacks should deploy in multiple regions

**Comment by abhinavGupta16** [comment]
We need the `rolename` defined for managing trust relationships with different stacks in `roleArn`. Any possible solutions on how we can export the auto-generated `rolename` to different stacks?

**Comment by gaiksaya** [comment]
Looks this is by design since role are manually updated in other AWS accounts for trust relationship. Even the deployments won't change the role name as such however, the blast radius is huge here. Considering that, closing this issue for now.
